# Generated by Django 5.0.6 on 2024-06-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                ('nutritional_value', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('ethnicity', models.CharField(max_length=200)),
                ('origin', models.CharField(max_length=200)),
            ],
        ),
    ]
